from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QAbstractItemView, QCheckBox, QComboBox, QDoubleSpinBox, QFormLayout, QGroupBox,
    QHBoxLayout, QHeaderView, QLabel, QLineEdit, QListWidget, QListWidgetItem, QMenu,
    QPlainTextEdit, QProgressBar, QPushButton, QScrollArea, QSlider, QSpinBox,
    QStackedWidget, QTableView, QVBoxLayout, QWidget,
)

from ..core import DEFAULT_OUTPUT, safe_int
from ..i18n import LANGUAGES, tr
from .accessibility import configure_accessible
from .speed_graph import SpeedGraphWidget
from .theme import THEMES
from .track_model import TrackTableModel


class MainWindowPagesMixin:
    """Large page builders extracted from the main orchestration window.

    The mixin creates the same widgets on ``self``; moving construction code out
    keeps signal ownership and runtime behavior unchanged while making
    ``main_window.py`` easier to audit and maintain.
    """
    def _build_book_tab(self) -> QWidget:
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.setSpacing(9)
        intro = QLabel(self._l("Вставьте ссылку на книгу или введите название/автора для поиска, затем выберите нужные части."))
        intro.setObjectName("secondaryText")
        intro.setWordWrap(True)
        layout.addWidget(intro)
    
        url_label = QLabel(self._l("Название, автор или ссылка:"))
        self.book_url_edit = QLineEdit()
        self.book_url_edit.setPlaceholderText(self._l("Название, автор или https://…"))
        self.book_url_edit.setMinimumHeight(38)
        configure_accessible(
            self.book_url_edit,
            name="Название, автор или ссылка на книгу",
            description="Введите название/автора для поиска или вставьте ссылку на поддерживаемый сайт",
            identifier="book_url",
        )
        url_label.setBuddy(self.book_url_edit)
        self.book_url_edit.returnPressed.connect(self.start_analysis)
        self.book_url_edit.textChanged.connect(self._book_url_changed)
        layout.addWidget(url_label)
        url_row = QHBoxLayout()
        url_row.addWidget(self.book_url_edit, 1)
        self.paste_url_button = QPushButton(self._l("Вставить"))
        configure_accessible(self.paste_url_button, name="Вставить ссылку из буфера обмена", identifier="paste_book_url")
        self.paste_url_button.clicked.connect(self.paste_book_url)
        url_row.addWidget(self.paste_url_button)
        self.clear_url_button = QPushButton(self._l("Очистить"))
        configure_accessible(self.clear_url_button, name="Очистить главное поле", identifier="clear_book_input")
        self.clear_url_button.clicked.connect(self.book_url_edit.clear)
        url_row.addWidget(self.clear_url_button)
        layout.addLayout(url_row)
    
        output_row = QHBoxLayout()
        output_row.addWidget(QLabel(self._l("Папка:")))
        self.book_output_edit = QLineEdit(str(self.settings.get("output_dir", DEFAULT_OUTPUT) or DEFAULT_OUTPUT))
        configure_accessible(self.book_output_edit, name="Папка для аудиокниг", identifier="book_output_dir")
        output_row.addWidget(self.book_output_edit, 1)
        self.output_choose_button = QPushButton(self._l("Выбрать…"))
        self.output_open_button = QPushButton(self._l("Открыть"))
        configure_accessible(self.output_choose_button, name="Выбрать папку для аудиокниг", identifier="book_choose_output")
        configure_accessible(self.output_open_button, name="Открыть папку для аудиокниг", identifier="book_open_output")
        self.output_choose_button.clicked.connect(lambda: self._choose_output_dir(target=self.book_output_edit))
        self.output_open_button.clicked.connect(self.open_output_folder)
        output_row.addWidget(self.output_choose_button)
        output_row.addWidget(self.output_open_button)
        layout.addLayout(output_row)
    
        self.recovery_panel = QWidget()
        self.recovery_panel.setObjectName("noticeCard")
        recovery_row = QHBoxLayout(self.recovery_panel)
        recovery_row.setContentsMargins(10, 7, 10, 7)
        self.unfinished_label = QLabel(self._l("Есть незавершённые загрузки"))
        configure_accessible(self.unfinished_label, name="Незавершённые загрузки", identifier="unfinished_status")
        self.recovery_button = QPushButton(self._l("Восстановить"))
        configure_accessible(
            self.recovery_button,
            name="Продолжить незавершённую загрузку",
            description="Найти resume.json, повторно проанализировать книгу и восстановить выбранные части",
            identifier="continue_unfinished",
        )
        self.recovery_button.clicked.connect(self.continue_unfinished)
        recovery_row.addWidget(self.unfinished_label)
        recovery_row.addStretch(1)
        recovery_row.addWidget(self.recovery_button)
        self.recovery_panel.setVisible(False)
        layout.addWidget(self.recovery_panel)
    
        row = QHBoxLayout()
        self.analyze_button = QPushButton(self._l("Анализировать"))
        self.analyze_button.setProperty("role", "primary")
        self.analyze_button.setEnabled(False)
        configure_accessible(
            self.analyze_button,
            name="Анализировать книгу",
            description="Получить сведения о книге и список доступных частей",
            identifier="analyze_book",
        )
        self.analyze_button.clicked.connect(self._analysis_primary_action)
        row.addWidget(self.analyze_button)
    
        # Kept as a hidden compatibility control for existing tests/shortcuts; the visible
        # analysis action is the single dynamic button above.
        self.cancel_analysis_button = QPushButton(self._l("Отменить анализ"), page)
        self.cancel_analysis_button.setVisible(False)
        self.cancel_analysis_button.setEnabled(False)
        self.cancel_analysis_button.clicked.connect(self.cancel_analysis)
        configure_accessible(self.cancel_analysis_button, name="Отменить анализ книги", identifier="cancel_analysis")
    
        row.addStretch(1)
        self.download_all_button = QPushButton(self._l("Скачать книгу"))
        self.download_all_button.setProperty("role", "primary")
        self.download_all_button.setMinimumWidth(180)
        self.download_all_button.setEnabled(False)
        self.download_all_button.clicked.connect(self._start_primary_download)
        configure_accessible(self.download_all_button, name="Скачать книгу", identifier="download_all")
        row.addWidget(self.download_all_button)
    
        self.download_menu_button = QPushButton("▾")
        self.download_menu_button.setFixedWidth(42)
        self.download_menu_button.setEnabled(False)
        configure_accessible(self.download_menu_button, name="Дополнительные варианты скачивания", identifier="download_options")
        download_menu = QMenu(self.download_menu_button)
        self.download_full_mp3_action = download_menu.addAction(self._l("Скачать одним MP3"))
        self.download_queue_action = download_menu.addAction(self._l("Добавить в очередь"))
        self.download_full_mp3_queue_action = download_menu.addAction(self._l("Добавить одним MP3 в очередь"))
        self.download_full_mp3_action.triggered.connect(self.start_full_mp3)
        self.download_queue_action.triggered.connect(self.add_current_to_queue)
        self.download_full_mp3_queue_action.triggered.connect(self.add_current_full_mp3_to_queue)
        self.download_menu_button.setMenu(download_menu)
        row.addWidget(self.download_menu_button)
    
        # Hidden compatibility buttons preserve the old action identifiers/hotkeys without
        # keeping seven controls visible in one row.
        self.download_button = QPushButton(self._l("Скачать выбранные"), page)
        self.full_mp3_button = QPushButton(self._l("Одним MP3"), page)
        self.add_queue_button = QPushButton(self._l("Добавить в очередь"), page)
        for hidden in (self.download_button, self.full_mp3_button, self.add_queue_button):
            hidden.setVisible(False)
            hidden.setEnabled(False)
        self.download_button.clicked.connect(self.start_download)
        self.full_mp3_button.clicked.connect(self.start_full_mp3)
        self.add_queue_button.clicked.connect(self.add_current_to_queue)
        configure_accessible(self.download_button, name="Скачать выбранные части", identifier="download_book")
        configure_accessible(self.full_mp3_button, name="Скачать книгу одним MP3", identifier="download_full_mp3")
        configure_accessible(self.add_queue_button, name="Добавить выбранные части в очередь", identifier="add_book_to_queue")
    
        self.cancel_download_button = QPushButton(self._l("Отменить скачивание"))
        self.cancel_download_button.setProperty("role", "danger")
        self.cancel_download_button.setEnabled(False)
        self.cancel_download_button.setVisible(False)
        configure_accessible(self.cancel_download_button, name="Отменить скачивание", identifier="cancel_download")
        self.cancel_download_button.clicked.connect(self.cancel_download)
        row.addWidget(self.cancel_download_button)
        layout.addLayout(row)
    
        self.analysis_progress = QProgressBar()
        self.analysis_progress.setRange(0, 1)
        self.analysis_progress.setValue(0)
        self.analysis_progress.setTextVisible(False)
        configure_accessible(self.analysis_progress, name="Ход анализа книги", identifier="analysis_progress")
        layout.addWidget(self.analysis_progress)
    
        self.download_stage_label = QLabel(self._l("Скачивание: не запущено"))
        configure_accessible(self.download_stage_label, name="Этап скачивания", identifier="download_stage")
        layout.addWidget(self.download_stage_label)
        self.download_progress = QProgressBar()
        self.download_progress.setRange(0, 100)
        self.download_progress.setValue(0)
        configure_accessible(self.download_progress, name="Ход скачивания", identifier="download_progress")
        layout.addWidget(self.download_progress)
    
        self.download_speed_label = QLabel(self._l("Скорость: —"))
        configure_accessible(self.download_speed_label, name="Скорость скачивания", identifier="download_speed")
        layout.addWidget(self.download_speed_label)
        self.speed_graph = SpeedGraphWidget(self)
        self.speed_graph.setVisible(False)
        layout.addWidget(self.speed_graph)
    
        self.book_empty_state = QLabel(self._l("Вставьте ссылку или введите название книги, чтобы начать."))
        self.book_empty_state.setObjectName("emptyState")
        self.book_empty_state.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.book_empty_state.setWordWrap(True)
        configure_accessible(self.book_empty_state, name=self._l("Вставьте ссылку или введите название книги, чтобы начать."), identifier="book_empty_state")
        layout.addWidget(self.book_empty_state)
    
        visual_row = QHBoxLayout()
        self.book_cover_label = QLabel(self._l("Нет обложки"))
        self.book_cover_label.setObjectName("coverPlaceholder")
        self.book_cover_label.setFixedSize(120, 120)
        self.book_cover_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.book_cover_label.setScaledContents(True)
        configure_accessible(self.book_cover_label, name="Обложка книги", identifier="book_cover")
        self.book_description = QLabel("")
        self.book_description.setWordWrap(True)
        configure_accessible(self.book_description, name="Описание книги", identifier="book_description")
        visual_row.addWidget(self.book_cover_label)
        visual_row.addWidget(self.book_description, 1)
        layout.addLayout(visual_row)
    
        self.book_summary = QLabel(self._l("Книга ещё не проанализирована."))
        self.book_summary.setWordWrap(True)
        self.book_summary.setObjectName("bookMetadata")
        configure_accessible(self.book_summary, name="Сведения о книге", identifier="book_summary")
        layout.addWidget(self.book_summary)
    
        narration_row = QHBoxLayout()
        self.narration_label = QLabel(self._l("Озвучка:"))
        self.narration_combo = QComboBox()
        configure_accessible(self.narration_combo, name="Вариант озвучки", identifier="narration_variant")
        self.narration_label.setBuddy(self.narration_combo)
        self.narration_combo.activated.connect(self._narration_selected)
        self.narration_available_button = QPushButton(self._l("Перейти к доступной озвучке"))
        configure_accessible(self.narration_available_button, name="Перейти к первой доступной озвучке", identifier="narration_first_available")
        self.narration_available_button.clicked.connect(self.select_first_available_narration)
        self.narration_label.setVisible(False)
        self.narration_combo.setVisible(False)
        self.narration_available_button.setVisible(False)
        narration_row.addWidget(self.narration_label)
        narration_row.addWidget(self.narration_combo, 1)
        narration_row.addWidget(self.narration_available_button)
        layout.addLayout(narration_row)
    
        select_row = QHBoxLayout()
        self.select_all_tracks_button = QPushButton(self._l("Выбрать все"))
        self.clear_tracks_button = QPushButton(self._l("Снять все"))
        self.play_selected_track_button = QPushButton(self._l("Воспроизвести выбранную"))
        self.select_all_tracks_button.setEnabled(False)
        self.clear_tracks_button.setEnabled(False)
        self.play_selected_track_button.setEnabled(False)
        self.select_all_tracks_button.clicked.connect(lambda: self._set_all_tracks_selected(True))
        self.clear_tracks_button.clicked.connect(lambda: self._set_all_tracks_selected(False))
        self.play_selected_track_button.clicked.connect(self.play_selected_track)
        configure_accessible(self.select_all_tracks_button, name="Выбрать все части", identifier="select_all_tracks")
        configure_accessible(self.clear_tracks_button, name="Снять выбор со всех частей", identifier="clear_all_tracks")
        configure_accessible(self.play_selected_track_button, name="Воспроизвести выбранную скачанную часть", identifier="play_selected_track")
        select_row.addWidget(self.select_all_tracks_button)
        select_row.addWidget(self.clear_tracks_button)
        select_row.addWidget(self.play_selected_track_button)
        select_row.addStretch(1)
        layout.addLayout(select_row)
    
        self.track_model = TrackTableModel(self)
        self.track_table = QTableView()
        self.track_table.setModel(self.track_model)
        self.track_table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.track_table.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.track_table.setAlternatingRowColors(True)
        self.track_table.verticalHeader().setVisible(False)
        self.track_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.ResizeToContents)
        self.track_table.horizontalHeader().setResizeContentsPrecision(60)
        self.track_table.horizontalHeader().setStretchLastSection(True)
        self.track_model.dataChanged.connect(self._track_selection_changed)
        self.track_table.selectionModel().selectionChanged.connect(self._update_selected_track_player_button)
        self.track_table.doubleClicked.connect(lambda _index: self.play_selected_track())
        self.track_table.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.track_table.customContextMenuRequested.connect(self._show_track_context_menu)
        configure_accessible(self.track_table, name="Части аудиокниги", identifier="book_tracks")
        layout.addWidget(self.track_table, 1)
    
        self.log_toggle_button = QPushButton(self._l("Показать технический журнал ▾"))
        self.log_toggle_button.setCheckable(True)
        self.log_toggle_button.setProperty("role", "flat")
        self.log_toggle_button.toggled.connect(self._toggle_session_log)
        configure_accessible(self.log_toggle_button, name="Показать или скрыть технический журнал", identifier="toggle_session_log")
        layout.addWidget(self.log_toggle_button)
        self.session_log_group = QGroupBox(self._l("Технический журнал"))
        log_layout = QVBoxLayout(self.session_log_group)
        self.session_log = QPlainTextEdit()
        self.session_log.setReadOnly(True)
        self.session_log.setMaximumBlockCount(1000)
        self.session_log.setMaximumHeight(180)
        configure_accessible(self.session_log, name="Технический журнал текущей сессии", identifier="session_log")
        log_layout.addWidget(self.session_log)
        self.session_log_group.setVisible(False)
        layout.addWidget(self.session_log_group)
        return page

    def _build_settings_tab(self) -> QWidget:
        page = QWidget()
        page_layout = QVBoxLayout(page)
        page_layout.setContentsMargins(0, 0, 0, 0)
        page_layout.setSpacing(10)
        outer = QHBoxLayout()
        outer.setSpacing(12)
        page_layout.addLayout(outer, 1)
    
        self.settings_nav = QListWidget(page)
        self.settings_nav.setObjectName("settingsNav")
        self.settings_nav.setFixedWidth(220)
        for label in ("Основные", "Загрузка и сеть", "Внешний вид и звук", "Интеграции и резервная копия"):
            QListWidgetItem(self._l(label), self.settings_nav)
        configure_accessible(self.settings_nav, name=self._l("Разделы настроек"), identifier="settings_sections")
        outer.addWidget(self.settings_nav)
    
        self.settings_stack = QStackedWidget(page)
        configure_accessible(self.settings_stack, name=self._l("Панель выбранного раздела настроек"), identifier="settings_stack")
        outer.addWidget(self.settings_stack, 1)
    
        def settings_page(title: str):
            scroll = QScrollArea(page)
            scroll.setWidgetResizable(True)
            scroll.setFocusPolicy(Qt.FocusPolicy.NoFocus)
            configure_accessible(scroll, name=title, identifier="settings_" + title.lower().replace(" ", "_"))
            content = QWidget(scroll)
            layout = QVBoxLayout(content)
            layout.setContentsMargins(8, 8, 8, 8)
            layout.setSpacing(8)
            scroll.setWidget(content)
            self.settings_stack.addWidget(scroll)
            return layout
    
        basic_layout = settings_page(self._l("Основные"))
        network_layout = settings_page(self._l("Загрузка и сеть"))
        appearance_layout = settings_page(self._l("Внешний вид и звук"))
        integration_layout = settings_page(self._l("Интеграции и резервная копия"))
    
        def group(target_layout, title: str):
            box = QGroupBox(title)
            form = QFormLayout(box)
            target_layout.addWidget(box)
            return form
    
        def add_combo(form, label: str, attr: str, options, setting_key: str, default, accessible_name: str, ident: str):
            widget = QComboBox()
            for text, value in options:
                widget.addItem(text, value)
            saved = self.settings.get(setting_key, default)
            idx = widget.findData(saved)
            widget.setCurrentIndex(max(0, idx))
            localized_accessible_name = str(label or "").rstrip(":：").strip() or accessible_name
            configure_accessible(widget, name=localized_accessible_name, identifier=ident)
            setattr(self, attr, widget)
            form.addRow(label, widget)
            return widget
    
        basic = group(basic_layout, self._l("Основные"))
        self.output_edit = QLineEdit(str(self.settings.get("output_dir", DEFAULT_OUTPUT)))
        configure_accessible(self.output_edit, name="Папка для аудиокниг", identifier="output_dir")
        browse = QPushButton(self._l("Выбрать папку"))
        configure_accessible(browse, name="Выбрать папку для аудиокниг", identifier="browse_output")
        browse.clicked.connect(self._choose_output_dir)
        output_row = QWidget()
        output_layout = QHBoxLayout(output_row)
        output_layout.setContentsMargins(0, 0, 0, 0)
        output_layout.addWidget(self.output_edit, 1)
        output_layout.addWidget(browse)
        basic.addRow(self._l("Папка загрузок:"), output_row)
    
        self.quality_combo = QComboBox()
        for text, value in ((self._l("Стандартное — оригинальное качество"), "standard"), (self._l("Для телефона — меньше размер"), "phone"), (self._l("Выравнять громкость"), "normalize")):
            self.quality_combo.addItem(text, value)
        current_audio = str(self.settings.get("audio_preset", "copy") or "copy")
        current_norm = str(self.settings.get("normalization_mode", "off") or "off")
        explicit_quality = str(self.settings.get("quality_preset", "") or "").strip()
        current_quality = (
            explicit_quality
            if explicit_quality in {"standard", "phone", "normalize"}
            else ("phone" if current_audio == "64k_mono" else ("normalize" if current_norm == "two_pass" else "standard"))
        )
        self.quality_combo.setCurrentIndex(max(0, self.quality_combo.findData(current_quality)))
        configure_accessible(self.quality_combo, name="Качество звука", identifier="quality_preset")
        self.quality_combo.currentIndexChanged.connect(self._quality_preset_changed)
        basic.addRow(self._l("Качество звука:"), self.quality_combo)
        add_combo(basic, self._l("Имя MP3:"), "naming_combo", [(self._l("Только номер"), "number"), (self._l("Номер и название части"), "number_title"), (self._l("Книга и номер"), "book_number")], "naming_mode", "number", "Схема имени MP3", "naming_mode")
        self.embed_tags_check = QCheckBox(self._l("Добавлять теги, автора и обложку в MP3"))
        self.embed_tags_check.setChecked(bool(self.settings.get("embed_tags", True)))
        configure_accessible(self.embed_tags_check, name="Добавлять теги и обложку в MP3", identifier="embed_tags")
        basic.addRow("", self.embed_tags_check)
        self.sidecars_check = QCheckBox(self._l("Сохранять metadata.json, NFO и описание книги"))
        self.sidecars_check.setChecked(bool(self.settings.get("save_sidecars", True)))
        configure_accessible(self.sidecars_check, name="Сохранять описание книги для медиатеки", identifier="save_sidecars")
        basic.addRow("", self.sidecars_check)
        self.delete_source_check = QCheckBox(self._l("Удалять временные исходные файлы после успешной обработки"))
        self.delete_source_check.setChecked(bool(self.settings.get("delete_source", True)))
        configure_accessible(self.delete_source_check, name="Удалять временные файлы после скачивания", identifier="delete_source")
        basic.addRow("", self.delete_source_check)
        self.clipboard_auto_check = QCheckBox(self._l("Предлагать открыть поддерживаемую ссылку из буфера обмена"))
        self.clipboard_auto_check.setChecked(bool(self.settings.get("clipboard_auto", True)))
        configure_accessible(self.clipboard_auto_check, name="Автоматически замечать ссылку в буфере обмена", identifier="clipboard_auto")
        basic.addRow("", self.clipboard_auto_check)
    
        audio = group(basic_layout, self._l("Качество и обработка звука"))
        add_combo(audio, self._l("Кодирование:"), "audio_preset_combo", [(self._l("Без перекодирования"), "copy"), ("MP3 64 kbps mono", "64k_mono"), ("MP3 96 kbps mono", "96k_mono"), ("MP3 128 kbps stereo", "128k_stereo")], "audio_preset", "copy", "Профиль кодирования звука", "audio_preset")
        add_combo(audio, self._l("Нормализация:"), "normalization_combo", [(self._l("Выключена"), "off"), (self._l("Один проход"), "single"), (self._l("Два прохода — точнее"), "two_pass")], "normalization_mode", "off", "Нормализация громкости", "normalization_mode")
    
        templates = group(basic_layout, self._l("Структура папок и файлов"))
        self.use_templates_check = QCheckBox(self._l("Использовать собственные шаблоны"))
        self.use_templates_check.setChecked(bool(self.settings.get("use_templates", False)))
        configure_accessible(self.use_templates_check, name="Использовать собственные шаблоны папок и файлов", identifier="use_templates")
        templates.addRow("", self.use_templates_check)
        self.folder_template_edit = QLineEdit(str(self.settings.get("folder_template", "{Book_Title}") or "{Book_Title}"))
        configure_accessible(self.folder_template_edit, name="Шаблон папки", identifier="folder_template")
        templates.addRow(self._l("Папка:"), self.folder_template_edit)
        self.track_template_edit = QLineEdit(str(self.settings.get("track_template", "{Track_Number}.mp3") or "{Track_Number}.mp3"))
        configure_accessible(self.track_template_edit, name="Шаблон имени MP3", identifier="track_template")
        templates.addRow(self._l("Имя MP3:"), self.track_template_edit)
        hint = QLabel(self._l("Доступно: {Author} {Book_Title} {Year} {Genre} {Narrator} {Track_Number} {Track_Title}"))
        hint.setWordWrap(True)
        templates.addRow("", hint)
        basic_layout.addStretch(1)
    
        network = group(network_layout, self._l("Сеть и Range-загрузка"))
        add_combo(network, self._l("Соединений:"), "segment_count_combo", [(self._l("Автоматически"), "auto"), ("1", "1"), ("2", "2"), ("4", "4"), ("8", "8")], "segment_count", "auto", "Количество параллельных соединений", "segment_count")
        add_combo(network, self._l("Range от размера:"), "segment_threshold_combo", [(f"{x} MB", x) for x in (4, 8, 16, 32, 64)], "segment_threshold_mb", 16, "Минимальный размер для Range-загрузки", "segment_threshold")
        add_combo(network, self._l("Порог медленного соединения:"), "auto_chunk_combo", [(f"{x} KB/s", x) for x in (128, 256, 512, 1024)], "auto_chunk_min_kbytes_per_sec", 256, "Порог медленного соединения", "auto_chunk_threshold")
        self.bandwidth_spin = QDoubleSpinBox()
        self.bandwidth_spin.setRange(0.0, 100.0)
        self.bandwidth_spin.setDecimals(1)
        self.bandwidth_spin.setSingleStep(0.5)
        self.bandwidth_spin.setSuffix(" MB/s")
        self.bandwidth_spin.setSpecialValueText(self._l("Без ограничения"))
        self.bandwidth_spin.setValue(float(self.settings.get("bandwidth_limit", 0.0) or 0.0))
        configure_accessible(self.bandwidth_spin, name="Ограничение скорости интернета", identifier="bandwidth_limit")
        network.addRow(self._l("Лимит скорости:"), self.bandwidth_spin)
        self.parallel_single_source_check = QCheckBox(self._l("Параллельно обрабатывать части на быстром SSD"))
        self.parallel_single_source_check.setChecked(bool(self.settings.get("parallel_single_source", False)))
        configure_accessible(self.parallel_single_source_check, name="Параллельная обработка на SSD", identifier="parallel_processing")
        network.addRow("", self.parallel_single_source_check)
        self.playwright_check = QCheckBox(self._l("Использовать браузерный резервный режим, если обычный анализ не сработал"))
        self.playwright_check.setChecked(bool(self.settings.get("playwright_fallback_enabled", True)))
        configure_accessible(self.playwright_check, name="Резервный браузерный анализ сайта", identifier="playwright_fallback")
        network.addRow("", self.playwright_check)
        network_layout.addStretch(1)
    
        ui = group(appearance_layout, self._l("Внешний вид"))
        self.language_combo = QComboBox()
        for code, label in LANGUAGES.items():
            self.language_combo.addItem(label, code)
        self._set_combo_data(self.language_combo, self.language)
        configure_accessible(self.language_combo, name=tr(self.language, "language"), identifier="language")
        self.language_combo.activated.connect(lambda _i: self.change_language())
        ui.addRow(tr(self.language, "language") + ":", self.language_combo)
        self.ui_mode_combo = QComboBox()
        self.ui_mode_combo.addItem(tr(self.language, "simple"), "easy")
        self.ui_mode_combo.addItem(tr(self.language, "advanced"), "advanced")
        self._set_combo_data(self.ui_mode_combo, self.settings.get("ui_mode", "easy"))
        configure_accessible(self.ui_mode_combo, name="Режим интерфейса", identifier="ui_mode")
        ui.addRow(self._l("Режим:"), self.ui_mode_combo)
        self.theme_combo = QComboBox()
        self.theme_combo.addItem(self._l("Системная"), "system")
        self.theme_combo.addItem(self._l("Светлая"), "light")
        self.theme_combo.addItem(self._l("Тёмная"), "dark")
        configure_accessible(self.theme_combo, name="Тема оформления", identifier="theme")
        saved_theme = str(self.settings.get("theme", "system") or "system").lower()
        self.theme_combo.setCurrentIndex(max(0, self.theme_combo.findData(saved_theme if saved_theme in THEMES else "system")))
        self.theme_combo.currentIndexChanged.connect(self._preview_theme)
        ui.addRow(self._l("Тема:"), self.theme_combo)
        self.scale_spin = QSpinBox()
        self.scale_spin.setRange(80, 200)
        self.scale_spin.setSingleStep(10)
        self.scale_spin.setSuffix(" %")
        self.scale_spin.setValue(max(80, min(200, safe_int(self.settings.get("scale", 100), 100))))
        configure_accessible(self.scale_spin, name="Масштаб интерфейса", description="Применится после перезапуска", identifier="ui_scale")
        ui.addRow(self._l("Масштаб:"), self.scale_spin)
        self.large_mode_check = QCheckBox(self._l("Крупный режим"))
        self.large_mode_check.setChecked(bool(self.settings.get("large_mode", False)))
        configure_accessible(self.large_mode_check, name="Крупный режим", identifier="large_mode")
        ui.addRow("", self.large_mode_check)
        self.hide_source_check = QCheckBox(self._l("Скрывать техническую колонку источника"))
        self.hide_source_check.setChecked(bool(self.settings.get("hide_source", False)))
        configure_accessible(self.hide_source_check, name="Скрывать техническую колонку источника", identifier="hide_source")
        ui.addRow("", self.hide_source_check)
        self.minimize_to_tray_check = QCheckBox(self._l("Сворачивать в трей во время длинной загрузки или очереди"))
        tray_available = self.tray_controller.available
        self.minimize_to_tray_check.setChecked(bool(self.settings.get("minimize_to_tray", True)) and tray_available)
        self.minimize_to_tray_check.setEnabled(tray_available)
        configure_accessible(self.minimize_to_tray_check, name="Сворачивать в системный трей во время длинной операции", identifier="minimize_to_tray")
        ui.addRow("", self.minimize_to_tray_check)
    
        sounds = group(appearance_layout, self._l("Звуки событий"))
        self.event_sounds_check = QCheckBox(self._l("Озвучивать события программы"))
        self.event_sounds_check.setChecked(bool(self.settings.get("event_sounds_enabled", True)))
        configure_accessible(self.event_sounds_check, name="Звуки событий включены", identifier="event_sounds_enabled")
        sounds.addRow("", self.event_sounds_check)
        self.event_sound_volume_slider = QSlider(Qt.Orientation.Horizontal)
        self.event_sound_volume_slider.setRange(0, 100)
        self.event_sound_volume_slider.setValue(max(0, min(100, safe_int(self.settings.get("event_sound_volume", 100), 100))))
        self.event_sound_volume_slider.setSingleStep(5)
        configure_accessible(self.event_sound_volume_slider, name="Громкость звуков событий", identifier="event_sound_volume")
        event_volume_holder = QWidget()
        event_volume_row = QHBoxLayout(event_volume_holder)
        event_volume_row.setContentsMargins(0, 0, 0, 0)
        event_volume_row.setSpacing(8)
        self.event_sound_volume_value_label = QLabel(f"{self.event_sound_volume_slider.value()}%")
        self.event_sound_volume_value_label.setMinimumWidth(42)
        self.event_sound_volume_value_label.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)
        configure_accessible(self.event_sound_volume_value_label, name=self._l("Текущая громкость звуков событий"), identifier="event_sound_volume_value")
        self.event_sound_volume_slider.valueChanged.connect(self._event_sound_volume_changed)
        def show_event_volume_tooltip(value):
            tooltip_fn = getattr(self, "_show_volume_tooltip", None)
            if callable(tooltip_fn):
                tooltip_fn(self.event_sound_volume_slider, value)

        self.event_sound_volume_slider.sliderMoved.connect(show_event_volume_tooltip)
        event_volume_row.addWidget(self.event_sound_volume_slider, 1)
        event_volume_row.addWidget(self.event_sound_volume_value_label)
        sounds.addRow(self._l("Громкость:"), event_volume_holder)
        sound_buttons = QWidget()
        sound_row = QHBoxLayout(sound_buttons)
        sound_row.setContentsMargins(0, 0, 0, 0)
        self.preview_voice_button = QPushButton(self._l("Проверить голос"))
        self.preview_system_button = QPushButton(self._l("Проверить системный звук"))
        configure_accessible(self.preview_voice_button, name="Прослушать голосовой звук события", identifier="preview_event_sound")
        configure_accessible(self.preview_system_button, name="Прослушать системный звук", identifier="preview_system_sound")
        self.preview_voice_button.clicked.connect(lambda: self._play_event_sound("app_ready", force=True))
        self.preview_system_button.clicked.connect(lambda: self.event_sound_manager.play_system("app_ready"))
        sound_row.addWidget(self.preview_voice_button)
        sound_row.addWidget(self.preview_system_button)
        sounds.addRow("", sound_buttons)
    
        appearance_layout.addStretch(1)
    
        abs_form = group(integration_layout, "Audiobookshelf")
        self.abs_enabled_check = QCheckBox(self._l("После скачивания запускать сканирование библиотеки Audiobookshelf"))
        self.abs_enabled_check.setChecked(bool(self.settings.get("abs_enabled", False)))
        configure_accessible(self.abs_enabled_check, name="Обновлять Audiobookshelf после скачивания", identifier="abs_enabled")
        abs_form.addRow("", self.abs_enabled_check)
        self.abs_url_edit = QLineEdit(str(self.settings.get("abs_url", "") or ""))
        self.abs_url_edit.setPlaceholderText("http://192.168.1.10:13378")
        configure_accessible(self.abs_url_edit, name="Адрес сервера Audiobookshelf", identifier="abs_url")
        abs_form.addRow(self._l("Адрес сервера:"), self.abs_url_edit)
        self.abs_api_key_edit = QLineEdit(str(self.settings.get("abs_api_key", "") or ""))
        self.abs_api_key_edit.setEchoMode(QLineEdit.EchoMode.Password)
        configure_accessible(self.abs_api_key_edit, name="API key Audiobookshelf", description=self._l("Секретное поле"), identifier="abs_api_key")
        abs_form.addRow("API key:", self.abs_api_key_edit)
        self.abs_library_id_edit = QLineEdit(str(self.settings.get("abs_library_id", "") or ""))
        configure_accessible(self.abs_library_id_edit, name=self._l("ID библиотеки Audiobookshelf"), identifier="abs_library_id")
        abs_form.addRow("Library ID:", self.abs_library_id_edit)
        self.abs_test_button = QPushButton(self._l("Проверить соединение"))
        configure_accessible(self.abs_test_button, name="Проверить соединение с Audiobookshelf", identifier="abs_test")
        self.abs_test_button.clicked.connect(self.test_audiobookshelf)
        abs_form.addRow("", self.abs_test_button)
    
        maintenance = group(integration_layout, self._l("Резервная копия"))
        backup_row = QWidget()
        backup_layout = QHBoxLayout(backup_row)
        backup_layout.setContentsMargins(0, 0, 0, 0)
        backup_button = QPushButton(self._l("Создать резервную копию"))
        restore_button = QPushButton(self._l("Восстановить из копии"))
        configure_accessible(backup_button, name="Создать резервную копию настроек, истории, позиций и Qt-очереди", identifier="create_backup")
        configure_accessible(restore_button, name="Восстановить резервную копию", identifier="restore_backup")
        backup_button.clicked.connect(self.create_backup)
        restore_button.clicked.connect(self.restore_backup)
        backup_layout.addWidget(backup_button)
        backup_layout.addWidget(restore_button)
        maintenance.addRow("", backup_row)
        integration_layout.addStretch(1)
    
        footer = QWidget(page)
        footer.setObjectName("settingsFooter")
        footer_layout = QHBoxLayout(footer)
        footer_layout.setContentsMargins(8, 8, 8, 8)
        footer_layout.addStretch(1)
        self.save_settings_button = QPushButton(self._l("Сохранить настройки"))
        self.save_settings_button.setProperty("role", "primary")
        self.save_settings_button.setMinimumWidth(190)
        configure_accessible(self.save_settings_button, name="Сохранить настройки", identifier="save_settings")
        self.save_settings_button.clicked.connect(self._save_settings)
        footer_layout.addWidget(self.save_settings_button)
        page_layout.addWidget(footer)
    
        self.settings_nav.currentRowChanged.connect(self.settings_stack.setCurrentIndex)
        self.settings_nav.setCurrentRow(0)
        return page


__all__ = ["MainWindowPagesMixin"]
